name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-java@v2
        with:
          channel: stable
          distribution: 'zulu'
          java-version: '11

      - name: Install dependencies
        run: flutter pub get

      - name: Build apk
        run: |
          dart format --set-exit-if-changed
          flutter analyze
          flutter test
          flutter build apk --debug
          flutter build appbundle

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
